### ISSUE TITLE
More documentation please

### ISSUE THREAD

**Issue by mgifford** [cloudfour/getAccessibilityTree-pleasantest-example#2]
I'd love more documentation on this than this blog post - https://cloudfour.com/thinks/accessibility-tree-snapshots-in-pleasantest/ and the README.

Is there more somewhere? I feel I'm missing something.

**Comment by calebeby** [comment]
Hi 👋 

The blog post is introducing a feature to [Pleasantest](https://github.com/cloudfour/pleasantest), our web testing tool. In the Pleasantest README there is documentation for all the functions. If you are looking for more of a getting-started guide for Pleasantest, the [Pleasantest introduction post](https://cloudfour.com/thinks/introducing-pleasantest/) is probably a good place to start (there is also a walkthrough video in the post).

This repo here is just a little demo for the blog post. Let me know if there is something specific more that you were expecting, happy to help out!

**Comment by mgifford** [comment]
I think @calebeby what would be useful for me is highlighting how pleasantest is different than jest-axe or even cypress-axe for testing.  And for that matter, why you are incorporating the Accessibility Tree into your testing plan. I get it, but many front end developers still haven't heard of the Accessibility Tree, so being explicit about what this will allow them to test for would be useful. 

Essentially, what is the sales pitch for adding Pleasantest to our current testing infrastructure? What will it give our front end team?

**Comment by calebeby** [comment]
Just to make sure we’re on the same page: Pleasantest is a testing tool in the same space as JSDOM, Cypress, etc. Pleasantest is not just getAccessibilityTree, getAccessibilityTree is just a recent feature we added to it.
[This section](https://github.com/cloudfour/pleasantest#comparisons-with-other-testing-tools) of the readme compares Pleasantest with other testing tools. That section was created before Pleasantest added the getAccessibilityTree feature, so it compares all the other aspects of Pleasantest with other testing tools.

With regards to why we have begun integrating accessibility tree snapshots into our testing plan and how accessibility tree snapshots differ from axe assertions:
- axe assertions are like a linter: They can check for specific common issues, but they cannot prove that your UI works and is accessible. [More about that here](https://github.com/nickcolley/jest-axe#%EF%B8%8F-this-project-does-not-guarantee-what-you-build-is-accessible). Accessibility tree snapshots help provide visibility into the accessible experience of using your website, in a way that makes it more clear when an element uses the wrong roles or is missing an accessible name, or isn’t structured in a sensible way.
- Pleasantest’s accessibility tree snapshots are not just for testing that your UI is accessible, they test that your UI works as expected. Whenever there are changes to the accessibility tree, the snapshot will flag the changes, and the test writer will have to approve the changes if they were intentional, or if they weren’t intentional fix them.
- If you want to use axe with Pleasantest, you can use [https://github.com/dequelabs/axe-core-npm/tree/develop/packages/puppeteer](https://github.com/dequelabs/axe-core-npm/tree/develop/packages/puppeteer). I can provide a code snippet for how to do that if it is helpful (it might be a good thing for me to add to the Pleasantest readme).

**Comment by mgifford** [comment]
Right..  Ok, that makes more sense now..  I think I came at this from an accessibility newsletter and have been trying to understand. This helps a lot. I don't think our team is using Pleasantest...  Least not yet.
